services:
  gateway:
    image: haproxy:3.2.6-alpine
    container_name: haproxy
    ports:
      - "8080:80"
    depends_on:
      - echo-service
    restart: "no"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  echo-service:
    image: python:3.14.0-alpine
    container_name: echo-service-haproxy
    volumes:
      - ../base/echo-service:/app
    working_dir: /app
    command: python server.py
