services:
  gateway:
    image: traefik:v3.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "8080:80"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf/dynamic_conf.yml:ro
    depends_on:
      - echo-a
      # - echo-b
      # - echo-c
    restart: "no"

  echo-a:
    build:
      context: ../base
      dockerfile: Dockerfile.http
    container_name: echo-http-a-traefik
    environment:
      - SERVICE_NAME=echo-A

  # echo-b:
  #   build:
  #     context: ../base
  #     dockerfile: Dockerfile.http
  #   container_name: echo-http-b-traefik
  #   environment:
  #     - SERVICE_NAME=echo-B

  # echo-c:
  #   build:
  #     context: ../base
  #     dockerfile: Dockerfile.http
  #   container_name: echo-http-c-traefik
  #   environment:
  #     - SERVICE_NAME=echo-C
