services:
  tyk-redis:
    image: redis:7-alpine
    container_name: tyk-redis
    ports:
      - 6379:6379

  gateway:
    image: tykio/tyk-gateway:v5.10.0
    container_name: tyk
    environment:
      TYK_GW_LISTENPORT: "80"
      TYK_GW_SECRET: "12345"
      TYK_GW_POLICIES_POLICYCONNECTIONSTRING: ""
    volumes:
      - ./tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
    depends_on:
      - tyk-redis
      - echo-service
    ports:
      - "8080:80"
    restart: "no"

  echo-service:
    image: python:3.14.0-alpine
    container_name: echo-service-tyk
    volumes:
      - ../base/echo-service:/app
    working_dir: /app
    command: python server.py
