services:
  gateway:
    image: caddy:2.8.4-alpine
    container_name: caddy
    ports:
      - "8080:80"
      # - "2019:2019"
    volumes:
      - ./${MODE}/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - echo-a
      - echo-b
    restart: "no"
    # environment:
      # CADDY_ADMIN: ":2019"

  echo-a:
    build:
      context: ../base
      dockerfile: Dockerfile.${MODE}
    container_name: echo-${MODE}-a-caddy
    environment:
      - SERVICE_NAME=echo-A
    ports:
      - "8081:5002"

  echo-b:
    build:
      context: ../base
      dockerfile: Dockerfile.${MODE}
    container_name: echo-${MODE}-b-caddy
    environment:
      - SERVICE_NAME=echo-B