services:
  gateway:
    image: nginx:1.29.3-alpine
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - echo-service
    restart: "no"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  echo-service:
    image: python:3.14.0-alpine
    container_name: echo-service-nginx
    volumes:
      - ../base/echo-service:/app
    working_dir: /app
    command: python server.py
